# Generated by Django 5.0.6 on 2024-08-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='productImg',
        ),
    ]
